---
- hosts: ipa
  strategy: free
  become: true
  gather_facts: false
  tasks:
  - name: Setting Up Python
    file:
      src: /usr/bin/python3.6
      path: /usr/bin/python
      state: link
  - name: Fixing hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      state: absent
  - name: Adding localhost IPV4 address to host file
    lineinfile:
      path: /etc/hosts
      line: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      create: yes
  - name: Adding localhost IPV6 address to host file
    lineinfile:
      path: /etc/hosts
      line: ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
      create: yes
  - name: Adding IPA address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.150 ipa.eight.example.com ipa
      create: yes
  - name: Adding system1 address to hosts file, Installing Packages...
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.151 system1.eight.example.com system1
      create: yes
  - name: Installing DL1 Stream And Packages
    shell: dnf install -y @idm:DL1; dnf install -y ipa-server ipa-server-dns bind-dyndb-ldap vsftpd createrepo pki-ca
    tags: repo
  - name: Downloading Repo Packages for System1
    shell: yum install -y man-pages httpd-manual bash-completion vdo stratis-cli stratisd bind-dyndb-ldap ipa-server ipa-server-dns --downloadonly --destdir=/var/www/html/rpms;
  - name: Configuring Repo For System
    command: createrepo /var/www/html/rpms
  - name: Enabling services
    service: name={{item}} enabled=true
    with_items:
      - httpd
      - vsftpd
      - firewalld
      - chronyd
  - name: Starting Firewalld
    service: name=firewalld state=started
  - name: Enabling Firewall Services
    command: firewall-cmd --permanent --add-service=http --add-service=https --add-service=ntp --add-service=dns --add-service=kerberos --add-service=ldap --add-service=ldaps --add-service=ftp
  - name: Reloading Firewall
    command: firewall-cmd --reload
  - name: Configuring network
    shell: nmcli con mod "System eth1" ipv4.addresses 192.168.55.150/24 ipv4.gateway 192.168.55.1 ipv4.dns 8.8.8.8 ipv4.dns-search eight.example.com ipv4.method manual
  - name: Reloaded Network.
    shell: nmcli con up "System eth1"  
  - name: Enabling IPV6
    shell: sysctl net.ipv6.conf.lo.disable_ipv6=0 ; sysctl net.ipv6.conf.all.disable_ipv6=0
  - name: Permissions Fixed. Configuring IPA server...(Est. Time - 7 minutes)
    shell: chmod 644 /usr/lib/python3.6/site-packages/urllib3/packages/ssl_match_hostname.py;chmod u+x /usr/lib/python3.6/site-packages/urllib3/packages/ssl_match_hostname.py 
  - name: Finishing IPA server Configuration
    shell: ipa-server-install --setup-dns --allow-zone-overlap --auto-reverse -a 'password' --hostname ipa.eight.example.com -r EIGHT.EXAMPLE.COM -p 'password' -n eight.example.com -U --forwarder 8.8.8.8
    ignore_errors: true
  - name: Restarting IPA Services
    shell: ipactl start --ignore-service-failure
  - name: Adding IPA user 'dave'
    ipa_user:
        name: dave
        state: present
        krbpasswordexpiration: 20200119235959
        givenname: dave
        sn: dave
        mail:
        - dave@eight.example.com
        telephonenumber:
        - '+555123456'
        sshpubkey:
        password: password
        uidnumber: 1001
        gidnumber: 1000
        ipa_host: ipa.eight.example.com
        ipa_user: admin
        ipa_pass: password
  - name: Adding IPA user 'lisa'
    ipa_user:
        name: lisa
        state: present
        krbpasswordexpiration: 20200119235959
        givenname: lisa
        sn: lisa
        mail:
        - lisa@eight.example.com
        telephonenumber:
        - '+555123456'
        sshpubkey:
        password: password
        uidnumber: 1002
        gidnumber: 1001
        ipa_host: ipa.eight.example.com
        ipa_user: admin
        ipa_pass: password   
  - name: Setting SELinux To Permissive
    shell: setenforce 0
#    async: 1500
#    poll: 0
#    register: ipa_config_sleeper
#    ignore_errors: yes
#  - name: Still Working On IPA Configuration...It takes time ¯\_(ツ)_/¯
#    async_status: jid={{ ipa_config_sleeper.ansible_job_id }}
#    register: job_result
#    until: job_result.finished
#    retries: 200
...