---
- hosts: system
  strategy: free
  gather_facts: False
  tasks:
  - name: Setting Up Python
    file:
      src: /usr/bin/python3.6
      path: /usr/bin/python
      state: link
  - name: Creating Temporary Repo File
    file:
      path: /etc/yum.repos.d/ipa.repo
      state: touch
      mode: 0755
  - name: Building Repo File
    blockinfile:
      dest: /etc/yum.repos.d/ipa.repo
      block: |
       [ipa]
       name=ipa repo
       baseurl=http://ipa.eight.example.com/rpms
       gpgcheck=0
       enabled=1
    tags: repo
  - name: Disabling services
    selinux:
      state: disabled
  - name: Fixing hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      state: absent
  - name: Rebuilding host file
    lineinfile:
      path: /etc/hosts
      line: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      create: yes
  - name: Adding IPA address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.150 ipa.eight.example.com ipa
      create: yes
  - name: Adding system IP address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.151 system.eight.example.com system
      create: yes
  - name: Configuring network
    command: nmcli con mod "System eth1" ipv4.addresses 192.168.55.151/24 ipv4.gateway 192.168.55.1 ipv4.dns 192.168.55.150 ipv4.dns-search eight.example.com ipv4.method manual
  - name: Saving network config
    command: nmcli con up "System eth1" 
  - name: Fixing Resolv File
    command: echo 'nameserver 192.168.55.150' > /etc/resolv.conf
  - name: Enabling Authconfig. Installing Environment Packages...
    command: authconfig --update --enablesssd --enablesssdauth --enablemkhomedir
  - name: Environment Packages Installed.
    shell: yum install -y man-pages 
    tags: repo
    async: 500
    poll: 0
    register: yum_sleeper
  - name: Finishing Environment Package Installation Before IPA Client Configuration
    async_status: jid={{ yum_sleeper.ansible_job_id }}
    register: job_result
    until: job_result.finished
    retries: 40  
  - name: Erasing Repos
    shell: rm -rf /etc/yum.repos.d/*
  - name: IPA client Configured
    command: ipa-client-install --enable-dns-updates --mkhomedir -N --principal admin --server ipa.eight.example.com -w password --hostname=system.eight.example.com --realm=EIGHT.EXAMPLE.COM --domain=eight.example.com -U
    ignore_errors: yes
    async: 500
    poll: 0
    register: ipa_sleeper
  - name: Enabling services
    service: name=firewalld enabled=true
  - name: Starting services
    service: name=firewalld state=started
  - name: Finishing IPA client configuration
    async_status: jid={{ ipa_sleeper.ansible_job_id }}
    register: job_result
    until: job_result.finished
    retries: 40
  - name: Erasing Repos
    shell: rm -rf /etc/yum.repos.d/*
  - name: Changing User Password
    shell: echo vagrant | sudo passwd vagrant --stdin
    tags: repo
  - name: Rebooting machine
    reboot:
      reboot_timeout: 60
  - name: Welcome to the RHCSA 8 Study/Test Environment!
    debug:
      msg:
        - 'Next Steps: Accessing The Systems:'
        - '- IPA - 192.168.55.150'
        - '- System 1 - 192.168.55.151'
        - '- Username - vagrant'
        - '- Password - vagrant'
        - '- For root - use `sudo` or `sudo su`'
        - '- Access example - `ssh vagrant@192.168.55.151`'
        - 'LDAP Users'
        - '- Username = dave, lisa'
        - '- Password = password'
        - 'Repo is available to use from `http://ipa.eight.example.com/rpms`'
        - '- Happy Studying!'
