---
- hosts: system
  strategy: free
  gather_facts: False
  become: true
  tasks:
  - name: Setting Up Python
    file:
      src: /usr/bin/python3.6
      path: /usr/bin/python
      state: link
  - name: Setting Hostname
    command: hostnamectl set-hostname system.eight.example.com
  - name: Configuring network
    command: nmcli con mod "System eth1" ipv4.addresses 192.168.55.151/24 ipv4.gateway 192.168.55.1 ipv4.dns 8.8.8.8 ipv4.method manual
  - name: Saving network config
    command: nmcli con up "System eth1" 
  - name: Erasing Repos
    shell: rm -rf /etc/yum.repos.d/*
  - name: Creating Temporary Repo File
    file:
      path: /etc/yum.repos.d/ipa.repo
      state: touch
      mode: 0755
  - name: Building Repo File
    blockinfile:
      dest: /etc/yum.repos.d/ipa.repo
      block: |
       [ipa]
       name=ipa repo
       baseurl=http://ipa.eight.example.com/rpms
       gpgcheck=0
       enabled=1
    tags: repo
  - name: Disabling services
    selinux:
      state: disabled
  - name: Fixing hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      state: absent
  - name: Rebuilding host file
    lineinfile:
      path: /etc/hosts
      line: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      create: yes
  - name: Adding IPA address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.150 ipa.eight.example.com ipa
      create: yes
  - name: Adding system IP address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.151 system.eight.example.com system
      create: yes
  - name: Enabling Authconfig. Installing Environment Packages...
    command: authconfig --update --enablesssd --enablesssdauth --enablemkhomedir
  - name: Environment Packages Installed.
    shell: yum install -y man-pages
  - name: Enabling services
    service: name=firewalld enabled=true
  - name: Starting services
    service: name=firewalld state=started
  - name: Erasing Repos
    shell: rm -rf /etc/yum.repos.d/*
    become: yes
  - name: Changing User Password
    shell: echo vagrant | sudo passwd vagrant --stdin
    become: no
  - name: Rebooting machine
    reboot:
      reboot_timeout: 120
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      mode: 0644
      block: |
         #!/bin/bash
         #
         echo -e '
         #          _           _           _    _          _      _           _       _
         #         / /\        /\ \        /\ \ /\ \    _ / /\    /\ \        /\ \    / /\
         #        / /  \      /  \ \      /  \ \\ \ \  /_/ / /   /  \ \      /  \ \  / /  \
         #       / / /\ \__  / /\ \ \    / /\ \ \\ \ \ \___\/   / /\ \ \    / /\ \ \/_/ /\ \
         #      / / /\ \___\/ / /\ \_\  / / /\ \_/ / /  \ \ \  / / /\ \_\  / / /\ \_\_\/\ \ \
         #      \ \ \ \/___/ /_/_ \/_/ / / /_/ / \ \ \   \_\ \/ /_/_ \/_/ / / /_/ / /    \ \ \
         #       \ \ \    / /____/\   / / /__\/ / \ \ \  / / / /____/\   / / /__\/ /      \ \ \
         #   _    \ \ \  / /\____\/  / / /_____/   \ \ \/ / / /\____\/  / / /_____/        \ \ \
         #  /_/\__/ / / / / /______ / / /\ \ \      \ \ \/ / / /______ / / /\ \ \         __\ \ \___
         #  \ \/___/ / / / /_______/ / /  \ \ \      \ \  / / /_______/ / /  \ \ \       /___\_\/__/\
         #   \_____\/  \/__________\/_/    \_\/       \_\/\/__________\/_/    \_\/       \_________\/
         '"#
         # You are logged into \"`hostname`\" as user \"`whoami`\"
         # This system is running `cat /etc/redhat-release`
         # kernel is `uname -r`
         #
         # For root - use \`sudo\` or \`sudo su -\`
         # Repo is available to use from http://ipa.eight.example.com/rpms
         # here are also two additional NICs.
         "
...